# Generated by Django 4.0.3 on 2022-04-12 12:44

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploadedFile',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='static/'), upload_to='UploadedFiles/'),
        ),
    ]
